### ISSUE TITLE
Not an issue, just a question ;-)

### ISSUE THREAD

**Issue by armin-reichert** [OrangoMango/Chess#1]
Dear Paul,

first of all, I am very impressed by your skills and your creativity.

I see that you publish your Java FX applications for all different platforms, even for the browser. My question to you is, how exactly do you create all these platform-specific versions? Is it possible to create all these, let's say from Windows? And for the browser version, do you use WebFX?

Thanks for your help and best regards from Germany!

Armin Reichert

**Comment by OrangoMango** [comment]
First of all, thank you very much for these kind words.
If I think that my app is worth it, I deploy it for Windows, Linux and Mac. I wrote a script that uses jdeps, jlink and jpackage to build a standalone executable for each platform (As I need that specific OS for every executable, I use github actions).
For the browser, there is a bit of more work to do. I use webFX that uses GWT. Most of the code keeps the same but I have to change some things and therefore it requires some time to make.
And if you are interested, for android I use javafxports.

Ich auch spreche Deutsch :)

**Comment by armin-reichert** [comment]
Hallo Paul,

vielen Dank für Deine Antwort. Wäre es möglich, dass ich Dein Skript an meinem Projekt (https://github.com/armin-reichert/pacman-javafx) ausprobieren kann? Ich bin nämlich vor wenigen Tagen auf Gradle umgestiegen und noch blutiger Anfänger (obwohl ich schon 57 Jahre alt bin ;-) Wo kann ich Dein Skript finden?

Mit WebFX habe ich bereits gearbeitet, siehe https://github.com/armin-reichert/webfx-pacman.

Beste Grüße
Armin

**Comment by OrangoMango** [comment]
Hallo Armin,
Wenn du willst, verleich es ist einfacher, wir können auf Discord sprechen (orango_mango). Ich kann dir dort alles erklären und das Skript geben.

**Comment by armin-reichert** [comment]
Hallo Paul,

ok.  Ich melde mich bei Dir.

Gruß Armin
